### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by Jothish21** [INFO526-DataViz/project-final-Plot-Pioneers#1]
The following is the peer review of the project proposal by Visual-Virtuosos. The team members that participated in this review are 

- Jothish Kumar Polaki - @Jothish21 
- Partha Koundinya P - @partha-pkp 
- Harshit Mehra - @harshitmehra1 
- Kashyap Sai Prasad Nadendla - @KashyapNadendla 
<BR>

- Describe the goal of the project.
     - To develop an engaging Shiny application that presents and assesses data from the World Happiness Report, allowing users to investigate and gain insights into the global factors influencing happiness.

- Describe the data used or collected.
    - The dataset provides a distinctive perspective on the elements that impact global happiness and overall well-being. 
    - It is sourced directly from the official World Happiness Report website, released annually by the United Nations, which offers comprehensive insights into the happiness and well-being status of various countries. 
    - The dataset is carefully curated, verified, and annually updated, ensuring its reliability for analysis.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

    - For question 1, the objective is to create an interactive experience for users to explore the influence of various factors on happiness scores in different countries and years. This will be achieved through the use of interactive widgets, such as drop-down menus for selecting specific years and countries. The visualization will include a Grouped Bar chart to illustrate the individual contributions of different factors to happiness scores and a stacked bar plot to show how these factors interact within the same bar. The ultimate goal is to identify and emphasize factors that consistently affect happiness scores across diverse countries and time periods.
    - For question 2, the analysis and visualization plan involves trend analysis using line graphs, focusing on pandemic periods, correlation and comparison through heatmaps and statistical tests, causal analysis with controls, and various visualizations. The Shiny app will feature an intuitive UI, reactive visuals, and interactive elements.

- Is there anything that is unclear from the proposal?
   - The proposal is detailed and clear.

- Provide constructive feedback on how the team might be able to improve their project.
    - We would appreciate if the dimensions of the data provided were laid in a tabular fashion, with smaller descriptions.
  

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
    - We are looking forward to the see the interactive shiny app with Grouped bar chart combination, and how it shows us the factors relation to happiness score.

- Provide constructive feedback on any issues with file and/or code organization.
   - It would have been good if inline code for loading the data-set has been presented on the proposal page.

- (Optional) Any further comments or feedback?
    - ALL THE BEST - Team Visual Virtuosos

**Comment by Chethana-16** [comment]
Thank You so much for your valuable review, we have made the changes suggested.
